version: '3.1'

services:
  main-db:
    image: mariadb:10
    restart: always
    ports:
      - '3306:3306'
    env_file: .env.database
    volumes:
      - ./data:/var/lib/mysql
      - ./schema/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
volumes:
  main-db:
    driver: local
